name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and Create User
        run: |
          # إنشاء المستخدم وصلاحيات الأدمن
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          
          # تفعيل الـ RDP في الويندوز والفايروال
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start RDP Tunnel (Pinggy)
        run: |
          # تشغيل النفق باستخدام SSH المدمج في الويندوز بدون أي برامج خارجية
          ssh -o StrictHostKeyChecking=no -R 0:127.0.0.1:3389 rdp.pinggy.io
